apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: eafad-api
  namespace: default
spec:
  selector:
    matchLabels:
      app: eafad-api
  replicas: 3 # tells deployment to run 6 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: eafad-api
    spec:
      volumes:
      - name: log-pv-storage
        persistentVolumeClaim:
            claimName: log-pv-claim
      containers:
      - name: eafad-api
        image: espekkaya/demo:v1.1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1
